### PR TITLE
New Super Function by Yusif. Please review

### PR DESCRIPTION
**Pull request by yusifrzayev**

### CODE REVIEW

**Review by StacyDb — DISMISSED** [review]
Please add info and Hello World

**Review by jule4ka881 — APPROVED** [review]
awesome Yusif

**Review by raffiGocer — APPROVED** [review]
LGTM

**Review by jule4ka881 — DISMISSED** [review]
can you add one more feature

**Review by alexmalai — APPROVED** [review]

**Review by StacyDb — COMMENTED** [review]
Cool

**Review by jule4ka881 — COMMENTED** [review]
image

**Review by jule4ka881 — COMMENTED** [review]
awesome

**Pull request merged**
